use crate::error::Result;
use crate::ingest::scanner::ParsedFile;
use crate::model::ResolvedUnit;
use naviscope_api::models::SymbolResolution;
use petgraph::stable_graph::NodeIndex;
use std::collections::HashMap;
use std::path::{Path, PathBuf};
use tree_sitter::Tree;

pub mod engine;
pub mod scope;

use crate::features::CodeGraphLike;

/// Core interface for resolving a symbol at a specific position in a document.
pub trait SemanticResolver: Send + Sync {
    /// Resolve a symbol at a specific position in a document (local view)
    fn resolve_at(
        &self,
        tree: &Tree,
        source: &str,
        line: usize,
        byte_col: usize,
        index: &dyn CodeGraphLike,
    ) -> Option<SymbolResolution>;

    /// Find nodes in the global graph matching a resolution result (global view)
    fn find_matches(&self, index: &dyn CodeGraphLike, res: &SymbolResolution) -> Vec<NodeIndex>;

    /// Resolve the type(s) of a symbol (e.g., return type of a method, type of a field)
    fn resolve_type_of(
        &self,
        index: &dyn CodeGraphLike,
        res: &SymbolResolution,
    ) -> Vec<SymbolResolution>;

    /// Find implementations or overrides of a symbol (global view)
    fn find_implementations(
        &self,
        index: &dyn CodeGraphLike,
        res: &SymbolResolution,
    ) -> Vec<NodeIndex>;
}

/// Project context generated by BuildResolver during the first phase
#[derive(Debug, Clone)]
pub struct ProjectContext {
    /// Mapping from path prefixes to module IDs (e.g., "/project/app" -> "module::app")
    pub path_to_module: HashMap<PathBuf, String>,
}

impl ProjectContext {
    pub fn new() -> Self {
        Self {
            path_to_module: HashMap::new(),
        }
    }

    /// Finds the best matching module ID for a given file path
    pub fn find_module_for_path(&self, path: &Path) -> Option<String> {
        let mut current = path.to_path_buf();
        while let Some(parent) = current.parent() {
            if let Some(id) = self.path_to_module.get(parent) {
                return Some(id.clone());
            }
            current = parent.to_path_buf();
        }
        None
    }
}

/// Responsible for resolution logic at the build tool level
pub trait BuildResolver: Send + Sync {
    /// Resolves build files into graph operations and project context
    fn resolve(&self, files: &[&ParsedFile]) -> Result<(ResolvedUnit, ProjectContext)>;
}

/// Responsible for resolution logic at the language level
pub trait LangResolver: Send + Sync {
    /// Resolves source files into graph operations using the provided context
    fn resolve(&self, file: &ParsedFile, context: &ProjectContext) -> Result<ResolvedUnit>;
}
